### ISSUE TITLE
Task Template

### ISSUE THREAD

**Issue by rgolovanov** [cvlabmiet/cvclasses16#16]
## Task

It is required to implement Demo application according to the Subj.
## Requirements

Demo application shall show how algorithm work step by step. See sample of the external [Region Growing Demo](https://www.youtube.com/watch?v=IjK774GwRGk).
- [ ] input image shall be loaded from the file specified in argv parameter.
- [ ] command line parser shall be used for parsing argc, argv parameters.
- [ ] If user input is required to specify seeds, starting points, etc. then UI shall handle mouse events.
- [ ] keyboard events shall be handled
  - [ ] to restore (R key) demonstration.
  - [ ] launch (Space key) demonstration.
  - [ ] next step (N key).
  - [ ] exit (ESC key) demonstration.
- [ ] print algorithm's execution time.
- [ ] dump initial image, image with user enter, all algorithm steps and overlaid colored segmentation over initial image: {algname_imgname_##.png}
- [ ] in thresholding methods separate window with histogram shall be shown
- [ ] histogram image also shall be dump in image file step by step.

Any question shall be discussed in comment to this issue or in group chat in VK.
## Pull request

[ ] Pull request shall contain algorithm description and screenshots of the intermediate pictures demonstrated how algorithm work.
### Checklist: Pull request shall:
- [ ] be assigned on reviewer which may be found from the group list = (Your# + Lesson# - 1) mod 8.
- [ ] have label according to the lesson.
- [ ] milestone according to the lesson.
- [ ] contain text (e.g. closes #1) in title which [trigger issue closing](https://help.github.com/articles/closing-issues-via-commit-messages/).

It is responsible of the student to push reviewer. When reviewer approves merge then "Pull Request" shall be assigned to the teacher (@rgolovanov).

**Application shall be implemented and code shall be reviewed before iteration end.**
