### ISSUE TITLE
Otsu Thresholding

### ISSUE THREAD

**Issue by rgolovanov** [cvlabmiet/cvclasses16#19]
## Task

It is required to implement Demo application according to the Subj.
## Requirements

Demo application shall show how algorithm work step by step. See sample of the external [Region Growing Demo](https://www.youtube.com/watch?v=IjK774GwRGk).
- [x] input image shall be loaded from the file specified in argv parameter.
- [x] command line parser shall be used for parsing argc, argv parameters.
- [ ] If user input is required to specify seeds, starting points, etc. then UI shall handle mouse events.
- [x] keyboard events shall be handled
  - [x] to restore (R key) demonstration.
  - [x] launch (Space key) demonstration.
  - [x] next step (N key).
  - [x] exit (ESC key) demonstration.
- [x] print algorithm's execution time.
- [x] dump initial image, image with user enter, all algorithm steps and overlaid colored segmentation over initial image: {algname_imgname_##.png}
- [x] in thresholding methods separate window with histogram shall be shown
- [x] histogram image also shall be dump in image file step by step.

Any question shall be discussed in comment to this issue or in group chat in VK.
## Pull request
- [x] Pull request shall contain algorithm description and screenshots of the intermediate pictures demonstrated how algorithm work.
### Checklist: Pull request shall:
- [x] be assigned on reviewer which may be found from the group list = (Your# + Lesson# - 1) mod 8.
- [x] have label according to the lesson.
- [x] milestone according to the lesson.
- [x] contain text (e.g. closes #1) in title which [trigger issue closing](https://help.github.com/articles/closing-issues-via-commit-messages/).

It is responsible of the student to push reviewer. When reviewer approves merge then "Pull Request" shall be assigned to the teacher (@rgolovanov).

**Application shall be implemented and code shall be reviewed before iteration end.**

**Comment by rgolovanov** [comment]
@whitemol по последнему пункту. Нужно писать не issue #19, а слово на выбор:
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
