### ISSUE TITLE
Gaussian Mixture Modelling

### ISSUE THREAD

**Issue by rgolovanov** [cvlabmiet/cvclasses16#20]
## Task

It is required to implement Demo application according to the Subj.
## Requirements

Demo application shall show how algorithm work step by step. See sample of the external [Region Growing Demo](https://www.youtube.com/watch?v=IjK774GwRGk).
- [x] input image shall be loaded from the file specified in argv parameter.
- [x] command line parser shall be used for parsing argc, argv parameters.
- [x] If user input is required to specify seeds, starting points, etc. then UI shall handle mouse events.
- [x] keyboard events shall be handled
  - [x] to restore (R key) demonstration.
  - [x] launch (Space key) demonstration.
  - [x] next step (N key).
  - [x] exit (ESC key) demonstration.
- [x] print algorithm's execution time.
- [x] dump initial image, image with user enter, all algorithm steps and overlaid colored segmentation over initial image: {algname_imgname_##.png}
- [x] in thresholding methods separate window with histogram shall be shown
- [x] histogram image also shall be dump in image file step by step.

Any question shall be discussed in comment to this issue or in group chat in VK.
## Pull request
- [x] Pull request shall contain algorithm description and screenshots of the intermediate pictures demonstrated how algorithm work.
### Checklist: Pull request shall:
- [x] be assigned on reviewer which may be found from the group list = (Your# + Lesson# - 1) mod 8.
- [x] have label according to the lesson.
- [x] milestone according to the lesson.
- [x] contain text (e.g. closes #1) in title which [trigger issue closing](https://help.github.com/articles/closing-issues-via-commit-messages/).

It is responsible of the student to push reviewer. When reviewer approves merge then "Pull Request" shall be assigned to the teacher (@rgolovanov).

**Application shall be implemented and code shall be reviewed before iteration end.**

**Comment by SergEfremenkov** [comment]
Здравствуйте. Я правильно понимаю, что математические ожидания и дисперсии объектов и фона нужно считать относительно заданного начального порога сегментации?

**Comment by rgolovanov** [comment]
Наоборот. Выбираются начальные матожидание и дисперсии. Далее решается задача минимизации - СКО реальной гистограммы и синтезированной должны быть минимальны.

 А порог рассчитывается вконце по пересечению Гауссиан.

**Comment by SergEfremenkov** [comment]
Вероятности принадлежности пикселя объекту или фону также задаются в самом начале? 
P.S.: Можете, пожалуйста, дать ссылку на источник, а то не могу найти описание данного метода в интернете.

**Comment by rgolovanov** [comment]
Идея сегментации с использованием смеси гауссиан в другом. Варьируя 2,3 и более гауссиан вы получаете синтезированную гистограмму (яркость пикселя по горизонтали и кол-во или доля пикселей в изображении с соотвествующей яркостью). Для простоты давайте брать 2 функции Гаусса - одна функция определяет фон, другая - объект. 

Далее необходимо изменять параметры гауссиан так, чтобы синтезированная гистограмма как можно лучше аппроксимировала бы реальную гистограму. Речи о вероятностях вообще нет.

Вот короткое [видео](https://www.youtube.com/watch?v=6pWHzLKjfTI), а вот [статья с описанием](https://pdfs.semanticscholar.org/bb75/c63ab57393b5bc36ea8f3d21b542740ba9e2.pdf).

**Comment by SergEfremenkov** [comment]
Большое спасибо.

**Comment by rgolovanov** [comment]
@SergEfremenkov я переоткрыл это задание, тк требуется обсуждение работы программы. Сейчас результаты сегментации выглядят неадекватными.

![gmm_ 99](https://cloud.githubusercontent.com/assets/14174584/19579741/de4dc834-972a-11e6-8b0b-71e179675a6d.png)

**Comment by rgolovanov** [comment]
по нажатию на пробел запускается новый цикл сегментации - случайным образом выбираются мат ожидания.
