### ISSUE TITLE
5. Robert's Cross vs DoG 3x3

### ISSUE THREAD

**Issue by rgolovanov** [cvlabmiet/cvclasses16#37]
## Task

It is required to prepare comparison report for algorithms in Subj.
## Requirements

Report shall demonstrate how algorithms work and answer the question: what algorithm is better?
- [ ] Prepare initial image satisfying following requirements:
  - shall contain any famous building or monument of your hometown;
  - 8-bit grayscale;
  - Size 512x512 pixels.
- [ ] Prepare binary image containing edges detected by human.
- [ ] Apply 1st and 2nd algorithm to the initial image with different thresholds [0:20:100].
- [ ] Calculate Precision and Recall metrics for each algorithm and threshold.
- [ ] Prepare plot (Python or Matlab) containig two curves (1st and 2nd algorithms) in axes: Precision and Recall.
- [ ] Explain results and answer main question.

Any question shall be discussed in comment to this issue or in group chat in VK.
## Pull request
- [ ] It shall contain full report in description with screenshots of initial image, edge detected by human, result images for each algorithm and plot with curves in axes Precision/Recall.
- [ ] It shall contain code based on lesson 3 which is used for creating images and metrics.
- [ ] It shall contain code of Matlab or Python script used for creating plot.
### Checklist: Pull request shall:
- [ ] have label according to the lesson.
- [ ] milestone according to the lesson.

"Pull Request" shall be assigned to the teacher (@rgolovanov).

**Application shall be implemented and code shall be reviewed before iteration end.**
