### ISSUE TITLE
7. Detect moving romb using GMM algorithm with background update

### ISSUE THREAD

**Issue by rgolovanov** [cvlabmiet/cvclasses16#54]
## Task

It is required to prepare report about background subtraction algorithm's work.
## Requirements

Report shall demonstrate how algorithms work with lifetime metrics.
- [ ] Use image from your report from Lesson3 to prepare synthetic video:
  - [x] Add some simple moving shape (rectangle or circle) which simulates moving (foreground) object.
  - [x] Fill moving shape with gray color which is not contrasting with background.
  - [x] Shape size shall be adequate to the simulating object.
  - [x] Object shall appear in the frame after a while, when detection algorithm will be completely initialized.
  - [x] Object shall move by the inclined line (not vertical and horizontal). Encouraged to use more complex trajectory.
  - [x] Object speed shall be such that object exist at the frame ~20sec.
- [x] Use background subtraction algorithm to detect moving object.
- [x] Calculate all complex metrics for each frame.
- [x] Prepare 7 plots with Metric's/Frame# curves..
- [x] Record the synthetic and segmented video and attach it to the report by link. 
- [x] Explain results.

Any question shall be discussed in comment to this issue or in group chat in VK.
## Pull request
- [x] It shall contain full report in description with screenshots of initial image,  link to synthetic and segmented video and plot with curves in axes Metric/Frame #.
- [x] It shall contain code based on lesson 4 containing a set of algorithms.
- [x] It shall contain code of Matlab or Python script used for creating plot.
### Checklist: Pull request shall:
- [x] have label according to the lesson.
- [x] milestone according to the lesson.

"Pull Request" shall be assigned to the teacher (@rgolovanov).

**Application shall be implemented and code shall be reviewed before iteration end.**

**Comment by rgolovanov** [comment]
Leave a comment
