### ISSUE TITLE
SIFT feature detection algorithm demo

### ISSUE THREAD

**Issue by rgolovanov** [cvlabmiet/cvclasses16#63]
## Task

It is required to prepare demo application and report about feature detection and matching algorithm's work.
## Requirements

Application shall demonstrate how algorithms work.
- [x] Use Reference (REF) and Test  (TST) images from [following URL](https://drive.google.com/open?id=0B-3W-pT_6OLcamN3NWVFR1A0Y0k).
- [x] Implement feature detection and descriptor algorithms specified in subj.
- [x] Implement feature matching algorithms. A window with difference between REF and TST shall be shown as a result.
- [x] The window with REF image shall contain controls to change parameters of detection algorithm.
- [x] The window with Diff image shall contain controls to change parameters of matching algorithm.
- [x] Console output shall contain following information:
  - [x] Feature detection algorithm name and parameters.
  - [x] The number of detected features for REF image and processing time.
  - [x] The number of detected features for TST image and processing time.
  - [x] Feature matching algorithm name and parameters.
  - [x] The number of matched pairs.
  - [x] Per iteration:iteration number,number of used pairs, number of rejected pairs, MSE(DIFF), processing time.

Any question shall be discussed in comment to this issue or in group chat in VK.
## Pull request
- [x] It shall contain full report in description with screenshots of:
  - [x] REF image with marked feature points.
  - [x] TST image with marked feature points.
  - [x] Result of matching features as difference between images.
  - [x] Plot with MSE (TST-REF) for each iteration of transform estimating procedure (RANSAC or ICP).
- [x] It shall contain C++ code in *lesson6* project.
- [ ] Python or Matlab code for creating plot of MSE (TST - REF)

### Checklist: Pull request shall:
- [x] have label according to the lesson.
- [x] milestone according to the lesson.

"Pull Request" shall be assigned to the teacher (@rgolovanov).

**Application shall be implemented and code shall be reviewed before iteration end.**
