### ISSUE TITLE
Surveillance System

### ISSUE THREAD

**Issue by rgolovanov** [cvlabmiet/cvclasses16#67]
## Task

It is required to develop **Surveillance System** which should track moving object and alarm if object is stopped. This task is common for all students, but each student should provide individual solution in separate Pull-request.

## Requirements

Report shall demonstrate how system works.
- [x] Use your image and moving object from lesson 4.
- [x] Add contrast border and diagonals to your object.
- [x] Change object movements so it will stop for 5-10sec in the middle of the way.
- [ ] Use any feature detector to find features, e.g. Harris or yours from lesson5-6.
- [ ] Apply Lucas-Kanade algorithm existed in lesson 7 demo or any other to track features.
- [ ] Feature points shall be marked with small green cirle.
- [ ] Moving object shall be round with red rectangle when system detect if it is stopped.

Any question shall be discussed in comment to this issue or in group chat in VK.
## Pull request
- [ ] Description of the system:
      - What feature points detector is used.
      - What feature tracker is used.
      - How system detects stopped object.
      - Screenshots:
            * Moving object before stop.
            * Stopped object.
            * Moving object after stop.  
- [ ] Link to video.

### Checklist: Pull request shall:
- [ ] have label according to the lesson.
- [ ] milestone according to the lesson.

"Pull Request" shall be assigned to the teacher (@rgolovanov).

**Application shall be implemented and code shall be reviewed before iteration end.**
